name: Checks

on:
  pull_request: { branches: [main] }
  push: { branches: [main] }

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build & Package
        run: npm run package
      - name: Check for changes
        run: git diff --exit-code ./dist/

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run this action
        uses: ./
